package main

var javascripts = []string{
	"assets/js/jquery.js",
	//= require jquery_ujs
	"assets/js/jquery.easing.js",
	"assets/js/jquery-ui.min.js",
	"assets/js/bootstrap.min.js",
	"assets/js/jquery.flexslider.js",
	"assets/js/background-check.min.js",
	"assets/js/jquery.fitvids.js",
	"assets/js/jquery.viewportchecker.js",
	"assets/js/jquery.stellar.min.js",
	"assets/js/wow.min.js",
	"assets/js/jquery.colorbox-min.js",
	"assets/js/owl.carousel.min.js",
	"assets/js/isotope.pkgd.min.js",
	"assets/js/masonry.pkgd.min.js",
	"assets/js/imagesloaded.pkgd.min.js",
	"assets/js/jPushMenu.js",
	"assets/js/jquery.fs.tipper.min.js",
	"assets/js/mediaelement-and-player.min.js",
	"assets/js/jquery.validate.min.js",
	"assets/js/theme.js",
	"assets/js/navigation.js",
	"assets/js/jquery.mb.YTPlayer.min.js",
	"assets/js/jquery.singlePageNav.js",
	"assets/js/contact-form.js",
	"assets/js/map.js",
	"assets/js/TweenLite.min.js",
	"assets/js/EasePack.min.js",
	"assets/js/pollyfill.js",
}

var stylesheets = []string{
	"assets/css/style.css",
	"assets/css/navigation.css",
	"assets/css/flexslider.css",
	"assets/css/owl.carousel.css",
	"assets/css/mediaelementplayer.css",
	"assets/css/colorbox.css",
	"assets/css/jquery.fs.tipper.css",
	"assets/css/bootstrap.css",
	"assets/css/font-awesome.css",
	"assets/css/ionicons.css",
	"assets/css/jPushMenu.css",
	"assets/css/animate.css",
	"assets/css/jquery-ui.css",
	"assets/css/emoji.css",
}
